pipelines:
  branches:
    develop:
      - step:
          name: Build and test
          image: adoptopenjdk/openjdk13:centos
          deployment: Test
          caches:
            - gradle
          script:
            - bash ./gradlew build
          artifacts:
            - build/**
      - step:
          name: Deploy
          image: python:3.7.4-alpine3.10
          services:
            - docker
          caches:
            - pip
          script:
            - pip3 install awscli
            - IMAGE="661143960593.dkr.ecr.us-west-2.amazonaws.com/mentorsuccess-server"
            - TAG="latest"
            - eval $(aws ecr get-login --no-include-email --region us-west-2 | sed 's;https://;;g')
            - docker build -t $IMAGE:$TAG .
            - docker push $IMAGE:$TAG
    master:
      - step:
          name: Build and test
          image: adoptopenjdk/openjdk13:centos
          deployment: Production
          caches:
            - gradle
          script:
            - bash ./gradlew build
          artifacts:
            - build/**
      - step:
          name: Deploy
          image: python:3.7.4-alpine3.10
          services:
            - docker
          caches:
            - pip
          script:
            - pip3 install awscli
            - IMAGE="661143960593.dkr.ecr.us-west-2.amazonaws.com/mentorsuccess-server"
            - TAG="prod"
            - eval $(aws ecr get-login --no-include-email --region us-west-2 | sed 's;https://;;g')
            - docker build -t $IMAGE:$TAG .
            - docker push $IMAGE:$TAG
